CREATE SEQUENCE address_id_seq AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE TABLE address
(
    id           BIGINT GENERATED BY DEFAULT AS SEQUENCE address_id_seq PRIMARY KEY,
    street       VARCHAR(255),
    number       INT,
    complement   VARCHAR(255),
    neighborhood VARCHAR(255),
    city         VARCHAR(255),
    state        VARCHAR(2),
    person_id    BIGINT NOT NULL,
    FOREIGN KEY (person_id) REFERENCES person (id)
);